### ISSUE TITLE
原封不动地fork了您的代码，但是执行Actions的时候报错：

### ISSUE THREAD

**Issue by shiwanjun1995** [ruanyf/github-actions-demo#44]
<img width="1173" alt="截屏2024-03-26 下午7 34 45" src="https://github.com/ruanyf/github-actions-demo/assets/38515714/b562a7a2-dc68-4189-b3ba-a1dac4c8ec6c">

<img width="1400" alt="截屏2024-03-26 下午7 35 07" src="https://github.com/ruanyf/github-actions-demo/assets/38515714/7471e8fd-9a63-4fa6-8575-3b148a68936c">

老师能否帮忙看一下

**Comment by shiwanjun1995** [comment]
@ruanyf 这是哪里配置不对么

**Comment by shiwanjun1995** [comment]
阮老师有空看看不 @ruanyf

**Comment by ruanyf** [comment]
依赖的模块太老了。再拉一下代码，应该好了。

**Comment by shiwanjun1995** [comment]
> 依赖的模块太老了。再拉一下代码，应该好了。

可以了，非常感谢，我准备自己动手再实际操作下。

**Comment by shiwanjun1995** [comment]
我更新为 v4 版本的了，一直报错：
`name: Build and Deploy
on:
  push:
    branches:
      - main
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4

    - name: Install and Build
      run: |
        npm install
        npm run-script build

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.ACCESS_TOKEN }}
        branch: gh-pages
        folder: build
        clean: true
`
折腾了很久，后面勾选了这个正常了。
<img width="1169" alt="截屏2024-03-31 下午7 49 41" src="https://github.com/ruanyf/github-actions-demo/assets/38515714/e05907e8-8a02-4776-bcdd-2b92b5623487">
